//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module contador5(

	//////////// CLOCK //////////
	input 		          		clk,
	input								enableContador5,

	//////////// SEG7 //////////
	output  			  [6:0]   numero,

	//////////// KEY //////////
	input 		     			rstn
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire clock_out_divisor;
	


//=======================================================
//  Structural coding
//=======================================================


  divisor div (
    .clock_in(clk),
    .reset_n(rstn),
    .enable(enableContador5),
    .clock_out(clock_out_divisor)
  );
  
  counter cnt (
    .clk(clk),
    .rstn(rstn),
    .en(clock_out_divisor),
    .count(numero)
  );
endmodule
